### ISSUE TITLE
Add support to trustCommiters

### ISSUE THREAD

**Issue by jprecuch** [xalvarez/prevent-file-change-action#363]
**Is your feature request related to a problem? Please describe.**
Currently the action only trust PR authors. This means if somebody else commits to the PR even with trustedAuthors it will still fail the job.

so if user1 created PR but user2 commits to the affected file in his PR (and is trusted) the job fails
Would be easy to implement also trustedCommiter to this action?
So if commit inside of PR was created by this trustedCommiter it will not fail?

**Describe the solution you'd like**
It would be nice if we could specify also trustedCommiters

**Describe alternatives you've considered**
Creating separate action that will do check for modified files, who performed commit and then check if it is fine

**Comment by xalvarez** [comment]
It can be done, why not :slightly_smiling_face: but the logic needs some thinking.

In that case if for example we have a PR with committers A, B and C, and only A and B are "trustedComitters", then that check should fail because C also committed something in that PR.

At the same time, "trustedAuthors" should always have priority, so regardless of the value of "trustedComitters", if the PR was opened by a "trustedAuthor", the change should be accepted.

**Comment by xalvarez** [comment]
Hello @jprecuch, I was just thinking about it and I might not have understood the issue. If User A issues a PR and User A is a trustedAuthor, wouldn't that be sufficient (without having to add a trusted committers flag)?

**Comment by xalvarez** [comment]
I couldn't find the need for this feature and there's been lack of feedback so I'll close the issue.
